package validation

// validationMessages bag of mapping error messages for each validation rules.
var validationMessages = map[string]string{
	"required":             "parameter :attribute harus diisi dan tidak boleh kosong.",
	"int":                  "parameter :attribute harus berupa tipe data int.",
	"uint":                 "parameter :attribute harus berupa tipe data uint.",
	"string":               "parameter :attribute harus berupa tipe data string.",
	"float":                "parameter :attribute harus berupa tipe data float.",
	"slice":                "parameter :attribute harus berupa tipe data slice ([]intX []uintX []byte []string).",
	"between":              "parameter :attribute harus berupa angka dan berada di antara %v dan %v.",
	"max":                  "parameter :attribute harus kurang dari atau sama dengan %v.",
	"min":                  "parameter :attribute harus lebih dari atau sama dengan %v.",
	"email":                "parameter :attribute harus berupa alamat email yang valid.",
	"array":                "parameter :attribute harus berupa tipe data array atau slice.",
	"map":                  "parameter :attribute harus berupa tipe data map.",
	"file":                 "parameter :attribute harus merupakan file yang diunggah.",
	"image":                "parameter :attribute harus merupakan file gambar yang diunggah dan mendukung pemeriksaan akhiran file.",
	"date":                 "nilai parameter :attribute harus berupa tanggal dalam format yang valid.",
	"alpha":                "nilai parameter :attribute hanya boleh mengandung karakter alfabet.",
	"alpha_num":            "nilai parameter :attribute hanya boleh berisi huruf dan angka.",
	"alpha_dash":           "nilai parameter :attribute hanya boleh mengandung huruf, angka, dash ( - ), dan underscore ( _ ).",
	"json":                 "nilai parameter :attribute harus berupa string JSON yang valid.",
	"number":               "nilai parameter :attribute harus berupa string angka dan >= 0.",
	"full_url":             "nilai parameter :attribute harus berupa string URL lengkap (harus dimulai dengan http, https).",
	"ip":                   "nilai parameter :attribute harus berupa string alamat IP (v4 atau v6).",
	"ipv4":                 "nilai parameter :attribute harus berupa string alamat IP versi 4.",
	"ipv6":                 "nilai parameter :attribute harus berupa string alamat IP versi 6.",
	"bool":                 "parameter :attribute harus berupa tipe data boolean.",
	"required_if":          "parameter :attribute harus diisi karena field %v bernilai %v.",
	"required_unless":      "parameter :attribute harus diisi karena field %v tidak bernilai %v.",
	"required_with":        "parameter :attribute harus diisi karena salah satu parameter {values} terdeteksi ada.",
	"required_with_all":    "parameter :attribute harus diisi karena semua parameter {values} terdeteksi ada.",
	"required_without":     "parameter :attribute harus diisi karena salah satu parameter {values} terdeteksi tidak ada.",
	"required_without_all": "parameter :attribute harus diisi karena semua parameter {values} terdeteksi tidak ada.",
	"in":                   "parameter :attribute harus salah satu dari: %v.",
	"not_in":               "parameter :attribute tidak boleh salah satu dari: %v.",
	"starts_with":          "parameter :attribute harus diawali dengan: %v.",
	"ends_with":            "parameter :attribute harus diakhiri dengan: %v.",
	"eq":                   "parameter :attribute harus sama dengan %v.",
	"ne":                   "parameter :attribute tidak boleh sama dengan %v.",
	"lt":                   "parameter :attribute harus kurang dari %v.",
	"gt":                   "parameter :attribute harus lebih besar dari %v.",
	"len":                  "panjang parameter :attribute harus sama dengan %v.",
	"min_len":              "panjang parameter :attribute minimal %v.",
	"max_len":              "panjang parameter :attribute maksimal %v.",
	"gt_date":              "nilai parameter :attribute harus lebih besar dari tanggal %v.",
	"lt_date":              "nilai parameter :attribute harus kurang dari tanggal %v.",
	"gte_date":             "nilai parameter :attribute harus lebih besar dari atau sama dengan tanggal %v.",
	"lte_date":             "nilai parameter :attribute harus kurang dari atau sama dengan tanggal %v.",
	"eq_field":             "parameter :attribute harus sama dengan nilai dari %v.",
	"ne_field":             "parameter :attribute tidak boleh sama dengan nilai dari %v.",
	"gt_field":             "parameter :attribute harus lebih besar dari nilai dari %v.",
	"gte_field":            "parameter :attribute harus lebih besar dari atau sama dengan nilai dari %v.",
	"lt_field":             "parameter :attribute harus kurang dari nilai dari %v.",
	"lte_field":            "parameter :attribute harus kurang dari atau sama dengan nilai dari %v.",
}
